import { foldSql } from '../lib/fold.js';

/**
 * Migraciones de PostgreSQL, en orden. Nunca modifiques una ya publicada: añade una nueva al final.
 * Las aplicadas se registran en la tabla schema_migrations (ver db/index.ts).
 */
export const migrations: string[] = [
  /* sql */ `
  CREATE TABLE users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text NOT NULL UNIQUE,
    name          text NOT NULL,
    password_hash text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE settings (
    user_id          integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    default_engine   text NOT NULL DEFAULT 'ocrspace',
    ocr_language     text NOT NULL DEFAULT 'spa',
    auto_scan        boolean NOT NULL DEFAULT false,
    gemini_model     text NOT NULL DEFAULT 'gemini-2.5-flash',
    ocrspace_key_enc text,
    gemini_key_enc   text,
    updated_at       timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE groups (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       text NOT NULL,
    description text NOT NULL DEFAULT '',
    author      text NOT NULL DEFAULT '',
    category    text NOT NULL DEFAULT '',
    color       text NOT NULL DEFAULT 'green',
    total_pages integer,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_groups_user ON groups(user_id, updated_at DESC);
  CREATE INDEX idx_groups_category ON groups(user_id, category);

  -- Búsqueda de texto completo sin distinguir acentos: el título pesa más que el cuerpo.
  CREATE TABLE scans (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id    integer REFERENCES groups(id) ON DELETE CASCADE,
    position    integer NOT NULL DEFAULT 0,
    title       text NOT NULL DEFAULT '',
    text        text NOT NULL DEFAULT '',
    engine      text NOT NULL,
    language    text NOT NULL DEFAULT 'spa',
    word_count  integer NOT NULL DEFAULT 0,
    page_label  text NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    search      tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('simple', ${foldSql('title')}), 'A') ||
      setweight(to_tsvector('simple', ${foldSql('text')}), 'B')
    ) STORED
  );
  CREATE INDEX idx_scans_user ON scans(user_id, created_at DESC);
  CREATE INDEX idx_scans_group ON scans(group_id, position);
  CREATE INDEX idx_scans_search ON scans USING gin(search);

  CREATE TABLE analyses (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type text NOT NULL CHECK (target_type IN ('group', 'scan')),
    target_id   integer NOT NULL,
    mode        text NOT NULL CHECK (mode IN ('online', 'offline')),
    content     text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_analyses_target ON analyses(user_id, target_type, target_id, created_at DESC);

  -- Módulo de documentos. Los tipos predefinidos viven en el cliente; aquí solo los propios.
  CREATE TABLE doc_templates (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        text NOT NULL,
    emoji       text NOT NULL DEFAULT '📄',
    fields      text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_doc_templates_user ON doc_templates(user_id);

  CREATE TABLE documents (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_key  text NOT NULL,
    template_name text NOT NULL,
    title         text NOT NULL,
    fields        text NOT NULL,
    text          text NOT NULL DEFAULT '',
    engine        text NOT NULL DEFAULT 'manual',
    method        text NOT NULL DEFAULT 'manual',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_documents_user ON documents(user_id, template_key, created_at DESC);
  `,
];
